# Generated by Django 2.2.4 on 2019-12-15 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('image_principale', models.ImageField(upload_to='media/articles/%Y/%m/%d/')),
                ('texte', models.TextField()),
                ('date_publication', models.DateField(blank=True, default=datetime.datetime.now)),
                ('est_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
