# Generated by Django 2.2.4 on 2019-12-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('VISON', 'Vision'), ('ACTUALITES', 'Actualités')], default='ACTUALITES', max_length=100),
        ),
    ]
